name: Sync Fork

on:
  schedule:
    - cron: '0 18 * * *'   # every day at 18:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote remove upstream || true
          git remote add upstream https://github.com/MoonTechLab/LunaTV.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main || git checkout master
          git merge upstream/main --no-edit || git merge upstream/master --no-edit || true

      - name: Push changes back to fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main || git push origin master
