name: Sync Fork

on:
  schedule:
    - cron: '0 18 * * *'   # run every day at 18:00 UTC
  workflow_dispatch:        # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote remove upstream || true
          git remote add upstream https://github.com/MoonTechLab/LunaTV.git
          git fetch upstream

      - name: Find default branches
        id: branch
        run: |
          # Detect fork default branch
          fork_branch=$(git symbolic-ref --short refs/remotes/origin/HEAD | sed 's@^origin/@@')
          echo "FORK_BRANCH=$fork_branch" >> $GITHUB_ENV

          # Detect upstream default branch
          upstream_branch=$(git remote show upstream | sed -n '/HEAD branch/s/.*: //p')
          echo "UPSTREAM_BRANCH=$upstream_branch" >> $GITHUB_ENV

      - name: Merge upstream changes
        run: |
          git checkout $FORK_BRANCH
          git merge upstream/$UPSTREAM_BRANCH --no-edit || echo "No changes to merge"

      - name: Push changes back to fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin $FORK_BRANCH
